const FETCH_LEADS = 'FETCH_LEADS';
const FETCH_LEADS_SUCCESS = 'FETCH_LEADS_SUCCESS';
const FETCH_OPPORTUNITIES_SUCCESS = 'FETCH_OPPORTUNITIES_SUCCESS';

export default {
  FETCH_LEADS,
  FETCH_LEADS_SUCCESS,
  FETCH_OPPORTUNITIES_SUCCESS,
};
